# Beryllium

spacing         = 3
hide_ascii      = false
key_color       = "#E8A2AF"
separator       = ">"

[box]
border          = "plain"
visible         = false

[palette]
glyph           = "  "
visible         = true
size		= 13
[bar]
glyph           = " "
hide_delimiters = true
visible         = true

[box.inner_margin]
x               = 2
y               = 1

[custom_ascii]
color           = "#DDB6F2"
